export { type AdminCertificate } from "@/types/domain";

export const ADMIN_CERTIFICATES = {
  title: "Certificates",
  subtitle: "Manage your credentials and certifications.",
  addLabel: "Add Certificate",
  addTitle: "New Certificate",
  editTitle: "Edit Certificate",
  searchPlaceholder: "Search certificates...",
  emptyTitle: "No certificates found",
  emptyNote: "Try a different search or add a new certificate.",
  backLabel: "Back to Certificates",
  saveLabel: "Save Certificate",
  savingLabel: "Saving...",
  deleteLabel: "Delete",
  deleteConfirmLabel: "Ya, Hapus",
  deleteConfirmTitle: "Hapus Certificate?",
  deleteConfirmDescription: "Certificate akan dihapus secara permanen. Tindakan ini tidak dapat dibatalkan.",
  editLabel: "Edit",
  publishedLabel: "Published",
  draftLabel: "Draft",
  verifiedLabel: "Verified",
  notFoundTitle: "Certificate not found",
  notFoundNote: "The certificate you are looking for does not exist.",
  fieldTitle: "Title",
  fieldTitlePlaceholder: "e.g. AWS Certified Cloud Practitioner",
  fieldSlug: "Slug",
  fieldSlugPlaceholder: "e.g. aws-certified-cloud-practitioner",
  fieldIssuer: "Issuer",
  fieldIssuerPlaceholder: "e.g. Amazon Web Services (AWS)",
  fieldIssueDate: "Issue Date",
  fieldIssueDatePlaceholder: "e.g. March 2024",
  fieldPeriod: "Period",
  fieldPeriodPlaceholder: "e.g. Issued Mar 2024 · No Expiration",
  fieldCredentialId: "Credential ID (optional)",
  fieldCredentialIdPlaceholder: "e.g. AWS-CP-8F3K2Q1X",
  fieldCredentialUrl: "Credential URL (optional)",
  fieldCredentialUrlPlaceholder: "https://www.credly.com/",
  fieldThumbnail: "Thumbnail URL",
  fieldThumbnailPlaceholder: "https://images.example.com/cover.jpg",
  fieldLogoUrl: "Logo URL",
  fieldLogoUrlPlaceholder: "https://example.com/logo.png",
  fieldGallery: "Gallery Images",
  fieldGalleryPlaceholder: "Upload images to show in the certificate gallery",
  fieldSkills: "Skills",
  fieldSkillsPlaceholder: "Comma separated: Cloud Computing, AWS, Architecture",
  fieldSummary: "Summary",
  fieldSummaryPlaceholder:
    "One point per line.\nThese render on the certificate detail page.",
  fieldSummaryHint: "One point per line — rendered on the detail page.",
  fieldIsPublished: "Published",
  fieldOrder: "Order",
  fieldOrderHint: "Lower values appear first.",
} as const;
