// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // `migrate deploy` butuh advisory lock; PgBouncer transaction pooler
    // (DATABASE_URL, 6543) tidak bisa ambilnya sehingga deploy hang.
    url: process.env["DIRECT_URL"] ?? process.env["DATABASE_URL"],
  },
});
